#!/usr/bin/env python
# encoding: utf-8

# Capgemini (Brazil) - www.capgemini.com/br-pt
# "People matter, results count"

system:
    format_user_names: true
    csv:
        input:
            sep: "\t"
            encoding: "utf-16"
        output:
            sep: "\t"
            encoding: "utf-8"

spreadsheets:
    event:
        start_time: "17:00"
        end_time: "17:45"
        check_time_slot: true  # TODO: Experimental
        check_user_name: true  # TODO: Experimental
        check_user_name_similarity: 0.9
    attendance_list:
        user_name: "Full Name"
        user_action: "User Action"
        timestamp: "Timestamp"
        date: "Date"
        duration: "Uptime (min)"
        attendance: "Attendance"
